name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install root dependencies
        run: npm ci

      - name: Install backend dependencies
        run: npm --prefix backend ci

      - name: Lint frontend (if available)
        run: npm run lint || echo "frontend lint script not found"

      - name: Lint backend (if available)
        run: npm --prefix backend run lint || echo "backend lint script not found"

      - name: Build frontend
        run: npm run build

      - name: Build backend (if available)
        run: npm --prefix backend run build || echo "backend build script not found"

      - name: Run frontend tests (if any)
        run: npm test || echo "no frontend tests found"

      - name: Run backend tests (if any)
        run: npm --prefix backend test || echo "no backend tests found"